# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
    build:
        docker:
            - image: aheinous/quicklog-build:0.3
        steps:
            - checkout
            - run: make qkl-unittests-xml
            - run: make coverage-html
            - run: make complexity-html
            - run: make cppcheck
            - run: make tidy

            - store_test_results:
                path: buildresults/testresults
            - store_artifacts:
                path: buildresults/testresults
                destination: test-results
            - store_artifacts:
                path: buildresults/coverage
                destination: coverage
            - store_artifacts:
                path: buildresults/complexity
                destination: complexity
            - store_artifacts:
                path: buildresults/cppcheck
                destination: cppcheck
            - store_artifacts:
                path: buildresults/tidy
                destination: tidy


